# when removing SC or PVC, the bucket resources will be cleared and deleted together.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-obs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      # when the used storage space in a bucket reaches the upper limit of the bucket storage quota,
      # it will be unable to continue to write data.
      storage: 5Ti
  storageClassName: obs-sc
