kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sfs-turbo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500G
  storageClassName: sfs-turbo.csi.huaweicloud.com
